import os
import json
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from dotenv import load_dotenv
from app.rag import ask_stream

# Load env vars
load_dotenv()

app = FastAPI()

# Initialize FastAPI app


# Add CORS to allow frontend to access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class Query(BaseModel):
    question: str

@app.get("/")
def read_root():
    return {"status": "ok", "message": "BVIFSC RAG Backend is running"}

@app.get("/health")
def health_check():
    return {"status": "healthy"}

@app.post("/chat")
def chat(q: Query):
    return StreamingResponse(ask_stream(q.question), media_type="text/plain")

@app.get("/api/aml-content/{slug}")
def get_aml_content(slug: str):
    try:
        # Path to the JSON file generated by scrape_aml.py
        # backend/app/main.py is in f:\mithun\Bvifsc\backend\app
        # We need to go up to f:\mithun\Bvifsc\db\data\processed\pages
        
        # Get absolute path to the project root (backend folder)
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) # f:\mithun\Bvifsc\backend
        project_root = os.path.dirname(base_dir) # f:\mithun\Bvifsc
        
        file_path = os.path.join(project_root, "db", "data", "processed", "pages", f"{slug}.json")
        
        if not os.path.exists(file_path):
            return {"error": "Content not found", "slug": slug}
            
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data
    except Exception as e:
        return {"error": str(e)}

# Serve static files (PDFs) from db/data/raw/pdfs
# Need to construct the absolute path to avoid issues with CWD
base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) # f:\mithun\Bvifsc\backend
project_root = os.path.dirname(base_dir) # f:\mithun\Bvifsc
pdf_dir = os.path.join(project_root, "db", "data", "raw", "pdfs")

if os.path.exists(pdf_dir):
    app.mount("/pdfs", StaticFiles(directory=pdf_dir), name="pdfs")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
