from fastapi import FastAPI, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from app.rag import ask, chroma
import os
import shutil
import uuid
import json
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Load env vars
from dotenv import load_dotenv
load_dotenv()

app = FastAPI()

# Add CORS to allow frontend to access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def read_root():
    return {"status": "ok", "message": "BVIFSC RAG Backend is running"}

@app.get("/health")
def health_check():
    return {"status": "healthy"}

class Query(BaseModel):
    question: str

@app.post("/chat")
def chat(q: Query):
    # ask() now returns {"answer": ..., "sources": ...}
    return ask(q.question)

@app.get("/api/aml-content/{slug}")
def get_aml_content(slug: str):
    try:
        # Path to the JSON file generated by scrape_aml.py
        # backend/app/main.py is in f:\mithun\Bvifsc\backend\app
        # We need to go up to f:\mithun\Bvifsc\db\data\processed\pages
        
        # Get absolute path to the project root (backend folder)
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) # f:\mithun\Bvifsc\backend
        project_root = os.path.dirname(base_dir) # f:\mithun\Bvifsc
        
        file_path = os.path.join(project_root, "db", "data", "processed", "pages", f"{slug}.json")
        
        if not os.path.exists(file_path):
            return {"error": "Content not found", "slug": slug}
            
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data
    except Exception as e:
        return {"error": str(e)}

# Serve static files (PDFs) from db/data/raw/pdfs
from fastapi.staticfiles import StaticFiles
app.mount("/pdfs", StaticFiles(directory="../db/data/raw/pdfs"), name="pdfs")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
